# Uncomment the next line to define a global platform for your project
platform :ios, "9.0"
use_frameworks!

target 'iRate' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iRate
source 'https://github.com/CocoaPods/Specs.git'
pod 'AFNetworking', '~> 3.1'
pod 'ReactiveObjC', '~> 2.1.2'

end
